BOARD_TAG=adafruit_circuitplayground_m0
ABOVE=../..
ARDUINO_DIR=$(ABOVE)/arduino-1.8.7
ARDMK_DIR=$(ABOVE)/Arduino-Makefile
AVR_TOOLS_DIR=$(ABOVE)/arduino-1.8.7/hardware/tools/avr
ISP_PORT=/dev/ttyACM0
ARDUINO_LIBS=SPI Wire Adafruit_Circuit_Playground/

include $(ARDMK_DIR)/Sam.mk



